import aiosmtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from fastapi import HTTPException


async def send_summary_email(recipient_email: str, summary: str):
    """Send the AI-generated summary to the recipient via SMTP."""
    
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")
    sender_name = os.getenv("SENDER_NAME", "Sales Insight Automator")
    
    if not smtp_user or not smtp_password:
        raise HTTPException(status_code=500, detail="SMTP credentials not configured.")
    
    # Build email
    message = MIMEMultipart("alternative")
    message["Subject"] = "📊 Your AI Sales Insight Report"
    message["From"] = f"{sender_name} <{smtp_user}>"
    message["To"] = recipient_email
    
    # Plain text version
    plain_text = f"Sales Insight Report\n\n{summary}"
    
    # HTML version
    html_summary = summary.replace("\n", "<br>")
    html_body = f"""
    <html>
      <body style="font-family: Georgia, serif; max-width: 700px; margin: auto; padding: 32px; color: #1a1a1a;">
        <div style="border-left: 4px solid #0066cc; padding-left: 20px; margin-bottom: 24px;">
          <h1 style="font-size: 22px; color: #0066cc; margin: 0;">📊 AI Sales Insight Report</h1>
          <p style="color: #666; margin: 4px 0 0 0; font-size: 13px;">Generated by Rabbitt AI · Sales Insight Automator</p>
        </div>
        <div style="line-height: 1.8; font-size: 15px;">
          {html_summary}
        </div>
        <hr style="margin-top: 32px; border: none; border-top: 1px solid #eee;">
        <p style="color: #999; font-size: 12px;">This report was auto-generated by Rabbitt AI's Sales Insight Automator.</p>
      </body>
    </html>
    """
    
    message.attach(MIMEText(plain_text, "plain"))
    message.attach(MIMEText(html_body, "html"))
    
    try:
        await aiosmtplib.send(
            message,
            hostname=smtp_host,
            port=smtp_port,
            username=smtp_user,
            password=smtp_password,
            start_tls=True,
        )
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Email delivery failed: {str(e)}"
        )